name: qiskit-topological-codes-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - numpy
  - pydot
  - matplotlib
  - tqdm #required for benchmarking
  - notebook #not required
  - jupyter #not required
  - pip:
    - qiskit
    - retworkx
    - pylatexenc
